### ISSUE TITLE
Last build with error

### ISSUE THREAD

**Issue by diegostammer** [grafana/grafana-starter-datasource-backend#16]
Last build is in an error state

**Comment by marefr** [comment]
What do you mean? What doesn't work? Thanks

**Comment by diegostammer** [comment]
On Circle Ci build ended on error.

Em sex, 23 de out de 2020 22:06, Marcus Efraimsson <notifications@github.com>
escreveu:

**Comment by marefr** [comment]
Maybe related to https://github.com/grafana/grafana/issues/28395

**Comment by dprokop** [comment]
Fixed with https://github.com/grafana/grafana-starter-datasource-backend/commit/fe65385fa5f01ee0c4e49038a355147f28f6d748
